##  RAII
### 아래의 소스는 문제가 없다 Test의 소멸자도 호출되고 throw catch도 가능하게 된다.
```

class Test
{
public:
	~Test()
	{
		cout << "~Test" << endl;
	}
};
void func()
{
	throw "exception";
}

int main()
{
	try
	{
		Test t;
		func();
	}
	catch (const char* e)
	{
		cout << e << endl;
	}
}
```
#### 하지만 동적으로 할당 받게 되면 소멸자가 호출되지 않는다.
```
class Test
{
public:
	~Test()
	{
		cout << "~Test" << endl;
	}
};
void func()
{
	throw "exception";
}

int main()
{
	try
	{
		Test* t = new Test;
		func();
	}
	catch (const char* e)
	{
		cout << e << endl;
	}
}
```
#### 이 문제를 해결하기 위해 도입된 기법이 RAII 이다.
#### 직역하면 리소스를 얻는 것은 초기화 한다는 뜻이다.
#### RAII 를 사용하지 않고 해결하려면 이런식으로 작성해주면 된다.
```
void func()
{
	throw "exception";
}

int main()
{
	int* i = nullptr;
	try
	{
		i = new int;
		func();
	}
	catch (const char* e)
	{
		delete i;
		cout << e << endl;
	}
}
```
#### 하지만 catch문이 여러개가 된다면 익셉션마다 해줘야 하는 불편함이 있고
#### 동적으로 변수 하나만 추가해도 계속 익셉션마다 delete를 해줘야 하고 exception이 호출 안될 경우에도 delete를 해줘여 하니 불편하다 

#### RAII를 통해 구현한다
```
class RAII
{
public:
	int* i;
	RAII()
	{
		i = new int;
	}
	~RAII()
	{
		cout << "~RAII" << endl;
		delete i;
	}
};

void func()
{
	throw "exception";
}

int main()
{
	try
	{
		RAII raii;
		func();
	}
	catch
}
```
#### RAII자체가 자동지역 변수이기 때문에 scope를 벗어나는 순간 소멸자를 호출하는 메커니즘을 이용해여 리소스를 해제시켜주는 것을 RAII라고 한다.
```
class Test
{
public:
	Test();
	~Test()
	{
		cout << "~Test" << endl;
	}
};
void func()
{
	throw "exception";
}

int main()
{
	try
	{
		std::unique_ptr<Test> test(new Test());
		func();
	}
	catch
}
```
#### unique_ptr를 사용해서 구현이 가능하다.
